---
- name: play for all host
  hosts: all
  roles:
    - { role: rc-local, tags: ['rc-local', 'redis'] }
    - { role: docker, tags: ['docker'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: mysql, tags: ['mysql'] }
    - { role: redis, tags: ['redis'] }
    - { role: rabbitmq, tags: ['rabbitmq'] }
    - { role: nacos, tags: ['nacos'] }

