---
mysqlVersion: 5.7.27
mysqlContainerName: mysql
mysqlPort: 3306
mysqlCharacterSetServer: utf8mb4
msyqlCollationServer: utf8mb4_unicode_ci
mysqlDataDir: /data/var/lib/mysql
mysqlConfDir: /data/etc/mysql/conf.d
mysqlConfMysqld:
  max_connections: 500
  skip_name_resolve: "true"